apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: patient-web-ingress
  namespace: app
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:597106152264:certificate/6eecdf13-ea45-4847-964b-ae9642308f87
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
spec:
  ingressClassName: alb
  rules:
    - host: www.kuspitalsoldeskproject.org
      http:
        paths:
          - path: /api/bff/patient
            pathType: Prefix
            backend:
              service:
                name: bff-svc
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: patient-web-svc
                port:
                  number: 8080